@startuml
class Ingredient {
    +ingredientId : String
    +name : String
    +measuringUnit : String
    +quantityInStock : Numeric
}

class Dish {
    +dishId : String
    +name : String
}

class Table {
    +tableId : String
    +maxCapacity : Numeric
}

class Meal {
    +mealId : String
    +date : Date
    +startTime : Time
    +endTime : Time
}

class Waiter {
    +waiterId : String
    +name : String
    +address : String
    +phoneNumber : String
}

class Client {
    +taxId : String
    +name : String
    +address : String
}

Ingredient "0..*" -- "0..*" Dish : uses >
Dish "1" -- "0..*" Meal : part of >
Table "1" -- "0..*" Meal : hosts >
Meal "1" -- "1" Waiter : served by >
Meal "1" -- "0..1" Client : associated with >
Meal "0..*" -- "0..*" Dish : consumed >
@enduml
