@startuml

class Scene {
    - code: String
    - description: String
    - setupList: List<Setup>
    + addSetup(setup: Setup): void
    + removeSetup(setup: Setup): void
    + getSetups(): List<Setup>
    + getDescription(): String
    + getCode(): String
}

class Setup {
    - code: String
    - photographicParameters: String
    - scene: Scene
    - takeList: List<Take>
    + addTake(take: Take): void
    + removeTake(take: Take): void
    + getTakes(): List<Take>
    + getPhotographicParameters(): String
    + getCode(): String
}

class Take {
    - number: int
    - filmLength: double
    - reelCode: String
    - setup: Setup
    + getFilmLength(): double
    + getReelCode(): String
    + getNumber(): int
}

class Location {
    - code: String
    - address: String
    - description: String
    + getAddress(): String
    + getDescription(): String
    + getCode(): String
}

class Internal {
    - scene: Scene
    + getScene(): Scene
}

class External {
    - scene: Scene
    - location: Location
    + getScene(): Scene
    + getLocation(): Location
}

class DayScene {
    - external: External
    + getExternal(): External
}

class NightScene {
    - external: External
    + getExternal(): External
}

Scene *-- "1..*" Setup
Scene <|-- Internal
Scene <|-- External
Setup *-- "1..*" Take
External --> "1" Location
External <|-- DayScene
External <|-- NightScene

@enduml